### ISSUE TITLE
Multiple layers of QR images are shown when click on extension icon several times

### ISSUE THREAD

**Issue by constgen** [atomspaceodua/qr-extension#13]
If user clicks several times to generate a QR image from an address many layers are shown one over another. See the screenshot for every click

![1](https://user-images.githubusercontent.com/673144/40587019-871de368-61d2-11e8-8917-94797498d527.png)
![2](https://user-images.githubusercontent.com/673144/40587020-88b691de-61d2-11e8-9401-49aa0f2b8af1.png)
![3](https://user-images.githubusercontent.com/673144/40587021-89d7aeea-61d2-11e8-8df3-e1c7807e8fb1.png)

**Expected result:** New QR image should replace old one

**Comment by Artefall** [comment]
Bug was fixed. Thank you for your attention.

**Comment by constgen** [comment]
Verified. Don't close issues until they are verified
